### ISSUE TITLE
'search_coca' error

### ISSUE THREAD

**Issue by cyrilinguist** [ekbrown/byucorpora#1]
Hi Earl,

I'm novice with R and I have some trouble with your program; when I use the 'search_coca' function, it returns "Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called ‘stringi’"

Could you please help me?

Thanks in advance, Cyril

**Comment by ekbrown** [comment]
Cyril,

Sorry, but the interface to the BYU corpora changed in May 2016 and broke my package, as my package simply webscrapes KWIC results from the corpora. I haven't yet found the time to fix my package.

Earl

**Comment by cyrilinguist** [comment]
Hi Earl,

Thank you for your response.

Cyril
